# Generated by Django 6.0.4 on 2026-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
