# Generated by Django 6.0.4 on 2026-05-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_data', '0002_alter_educationmodel_name_alter_skillmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='short_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
