# Generated by Django 6.0.4 on 2026-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
