# Generated by Django 6.0.4 on 2026-05-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
