# Generated by Django 6.0.4 on 2026-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_candidate_parsed_data_delete_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='soft_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
