# Generated by Django 6.0.4 on 2026-05-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_candidate_parsed_data_soft_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_parsed_data',
            name='summary',
        ),
    ]
