# Generated by Django 6.0.4 on 2026-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_remove_candidate_parsed_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_parsed_data',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
