# Generated by Django 6.0.4 on 2026-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_candidate_parsed_data_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='address_idx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='email_idx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_parsed_data',
            name='phone_idx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
